### ISSUE TITLE
No compatibility with Nodejs 12

### ISSUE THREAD

**Issue by lemariva** [HilscherAutomation/netPI-nodered-fieldbus#1]
Nodejs 8.x LTS is almost at the end of the life-cycle. I tried to update the project to Nodejs 12.x but the compiled binary [fieldbus.node](https://github.com/HilscherAutomation/netPI-nodered-fieldbus/blob/master/node-red-contrib-fieldbus/lib/fieldbus.node) -fieldbusDLL- is not compatible. When are you planning to update this file? or Is it possible to get the source code to compile it?

**Comment by hilschernetpi** [comment]
Well, right now I see that not even Node-RED supports nodejs 12.x if I look here https://nodered.org/docs/faq/node-versions. So we will be thinking of nodejs version 12.x support if they change the status to supported or recommended. And right now I don't see the invest time into current version 10.x even if recommended since I see no advantage in doing so. Did you test 10.x by the way?

**Comment by lemariva** [comment]
Thank you for your prompt reply! 
I tested nodejs 10.x and 12.x and nodered@1.0.2 worked on both versions without any problem, but the fieldbus.node didn't work. Then, I chose v12.x because of the multithread support (on 10.x is only experimental).  

Is there any chance to get the source code of the fieldbus.node to compile it myself? 
Thanks in advance!

**Comment by hilschernetpi** [comment]
Since V8.x is EOL in January, I agree to look forward for a V12.x support. I gonna see to trigger now a recompilation of the sources and support for V12.x

**Comment by hilschernetpi** [comment]
I have now added nodejs V12.x compatibility.

**Comment by lemariva** [comment]
Thanks!
